name: Build and Test

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-24.04, windows-2025]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Setup Java
      uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
      with:
        distribution: temurin
        java-version: 21
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6.1.0
    - name: Build all classes
      run: ./gradlew classes
  test:
    strategy:
      matrix:
        os: [ubuntu-24.04, windows-2025]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    needs: build
    steps:
    - name: Checkout Repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Setup Java
      uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
      with:
        distribution: temurin
        java-version: 21
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6.1.0
    - name: Install Flox
      uses: flox/install-flox-action@6e70b2624cea62b0f11ea4a28e719fe1c86c028b # v2.4.1
      with:
        disable-metrics: true
      if: runner.os != 'Windows'
    - name: Run unit tests in a minimal environment
      run: ./flox/run_isolated.sh minimal ./gradlew --scan test jacocoTestReport
      if: runner.os != 'Windows'
    - name: Run unit tests
      run: ./gradlew --scan test jacocoTestReport
      if: runner.os == 'Windows'
    - name: Create Test Summary
      uses: test-summary/action@37b508cfee6d4d080eedd00b5bb240a6a784a6a5 # v2
      with:
        paths: "**/test-results/**/TEST-*.xml"
      if: always()
  funTest:
    runs-on: ubuntu-24.04
    needs: test
    steps:
    - name: Checkout Repository
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
    - name: Setup Java
      uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
      with:
        distribution: temurin
        java-version: 25
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@5e2ebd065dc2488b7a6ad670704656cbbe1e8f60 # v6.1.1
    - name: Run Scorecard functional tests
      run: ./gradlew :plugins:advisors:scorecard-advisor:funTest
    - name: Run CrOSSD functional tests
      run: ./gradlew :plugins:advisors:crossd-advisor:funTest
  lint:
    runs-on: ubuntu-24.04
    needs: funTest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
    - name: Setup Java
      uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
      with:
        distribution: temurin
        java-version: 25
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@5e2ebd065dc2488b7a6ad670704656cbbe1e8f60 # v6.1.1
    - name: Run detekt linter
      run: ./gradlew detekt
